name: Make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt install mtools
      
    - name: Build
      run: make && cd kernel && cat src/kernel.cpp
      
    - name: Download Output
      uses: actions/upload-artifact@v2
      with:
          name: Brick OS Output
          path: bin
          


